sudo: false
language: node_js
node_js:
- '4'
- '5'
- '6'
cache:
  directories:
  - node_modules
script:
- make lint
- make test
after_success:
- make coveralls
- '[[ -n "$TRAVIS_TAG" ]] && make gh-pages'
deploy:
  provider: npm
  email: rr.rossmann@gmail.com
  api_key:
    secure: ab6KQPc/4ASdXOkbIu0A1Eg9dJrTZsVUt/tK3NK8478f/hhxJAxC4DGkZuDVzAtvncSIUMgAzaE9/8l2ccLYGkLxT4dqtV2l0fyb31cpDL6Wziuv7jAQPwHDcuQkuK9le4wI8KHI0ClSrt9LADvlsWT/qssW9LDauqkuQn5PMkCNzkRVDyv7ua7OPjC8KtD1HMYMMZQ31olnFBtaR7a1PpUhCxj1JkaoP5fl5jE2EKFo85Gq6oi0q4UmXmrZyQ69K/5Vo57XcbiIv5t4qohcgOsDwZSW9XMb6H66hjbERmERMshsTS/fvAuyUSUncaD5d0DHfUzgXY+pxev/RYQ8E2AsuhovPnJAtqpuqao9Vy8isZQ3Go52f7M0jsg6+wY14b9/ApWT17n6mN789td/LdLJCTeOwh7rv1Hfc1qSmPULksxHk07SFAKq6EC+3JfHTPX9dghpfT3UhdBqCOr1Fl1wZ40DbI/bXaram0JLn+O1QL11hQQ3Dfzwae+ljj8cMpeUo1RHfWQuGI8U4lm2Ost5PPfUC+m78r/UlqpcASQ+MTNbxXNw2VW6C1ODqjtf+XOp5q1mKsU+xB3DcKZz60g5McyP8y8Z2d1t7gMk9kkBTb89lFzJqwnw+/0IC+ZcTGR2Qkm3MZ2Rcs/hSh6+aea54T/JUG0C1dTfY5Y3HYs=
  on:
    tags: true
    repo: nodestream/nodestream
    node: '6'
env:
  global:
    secure: xdbYxrFTSNtbYD244YGPy7rM9Zy7S3qs1pJkoxygk5e18vF/qD2xmo9rXvgMowAhf1SNX0Po/Ke2GrvJNF+JxOmvQypPOCxfB8nV5bu6aFu4FtzC2g3mlKiaVrLM8oJiLgB+1gGz2vqhiK5fonxCcrKm0xrc3VblnmQs6Gxb7PN5i5VPxkW0K5lzmOp8srQ1pZOflmsFji1ftIMUKEokgUme/DLBDxN/LMVC3YuedJlTFyOT8hQu5k/9CFmPWHeFeqXhBy2FJq3+QIjbGhuHoyBNCdf6rE04ZPR/dS42S/kgogOMOoz+ItdgZ3iDwF4WaYL9UIVFx8SqMcHZxxM7foQCeIo+rhEftuOfVl14FQyh0GS6hL2YhR7HxVfda1azl6pRQc1DQjmLig5OPSdF4M6K8o4wi5SCjeE6qw6vYDqj5zOD3Tcr80/0RIkjpEdczWH5Dl8XrBn9TpkekscKCu4/TGbnWXtJHJ5xYK1zlvKVY8Dk3FabIWWL8YwPfKBFFqLwgMH94PEKnEXeaGtWIZO+sCMTQKfOHgbjT39eIdVt7Wv6sRbz1grfDO9bEgjrdhF8h0iFqL6aBvENlCTIYE65ZBTDFj8szG9whL1ZC6VGxdqcJgplchvL7i7sHES3HmSioLGMwMAk3oV05mXIep+NGBecc+LupPKkWzI7alc=
